### ISSUE TITLE
Hardware defaults should merge with input

### ISSUE THREAD

**Issue by LecrisUT** [JM1/ansible-collection-jm1-libvirt#4]
https://github.com/JM1/ansible-collection-jm1-libvirt/blob/e119ccf4868eccc1c85f7e4b4ebdff4a7d54a8bf/plugins/modules/domain.py#L200-L205

In case the user does not override all of the default fields. Would that be better in Ansible or python?

**Comment by JM1** [comment]
We cannot merge user input with default fields because then users would have no way of removing fields they do not want to pass to `virt-install`. The current style follows Ansible's way of specifying defaults: Either do not specify parameter `hardware` and be happy with its default or specify `hardware` with the a value you want it to be.

**Comment by LecrisUT** [comment]
How about defining a `default_hardware` so that one can call a `set_facts` with `hardware | combine(default_hardware)` for the necessary role?

**Comment by JM1** [comment]
Customizations like virtual-machines-share-most-hardware-specs-but-differ-in-minor-aspects are better handled through inventory `group_vars` and `host_vars` instead of trying to add more and more variables to a role such as `jm1.libvirt.server`. 

`hardware` in `jm1.libvirt.server` already allows maximum flexibility and thus does not have to be extended. Adding more variables to that role to tweak `hardware` a bit for your use case will not add any flexibility for others, hence you are looking at the wrong place. Try to grasp the power of Ansible's variable system, variable precedence rules and inventories!
